/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import vistas.*;
/**
 *
 * @author DesktopG
 */
public class mnuAdmin extends javax.swing.JFrame {
    
   
    public mnuAdmin() {
        initComponents();
        
        //Fecha del Sistema
        Date fecha=new Date();
        SimpleDateFormat formato=new SimpleDateFormat("dd-MMMM-YYYY");
        lblFecha.setText(formato.format(fecha));
        //Hora del Sistema
        Timer tiempo=new Timer(100, new mnuAdmin.horas());
        tiempo.start();
        
    }
    class horas implements ActionListener {
        public void actionPerformed(ActionEvent e){
            Date hora=new Date();
            String pmam="hh:mm:ss a";
            SimpleDateFormat format=new SimpleDateFormat(pmam);
            Calendar hoy = Calendar.getInstance();
            lblHora.setText(String.format(format.format(hora), hoy));
            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        dskMenu = new javax.swing.JDesktopPane();
        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AgregarProductos = new javax.swing.JMenuItem();
        AgregarCategoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        AgregarEventos = new javax.swing.JMenuItem();
        jmiArqueo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        AdministrarUsuarios = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ReporteVentas = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de administración de ventas CECONEXPO");

        dskMenu.setToolTipText("");
        dskMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("nombreUsuario");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario Activo:");

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("FECHA");

        lblHora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("HORA");

        dskMenu.setLayer(lblUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskMenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskMenu.setLayer(lblFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskMenu.setLayer(lblHora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskMenuLayout = new javax.swing.GroupLayout(dskMenu);
        dskMenu.setLayout(dskMenuLayout);
        dskMenuLayout.setHorizontalGroup(
            dskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 704, Short.MAX_VALUE)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dskMenuLayout.setVerticalGroup(
            dskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dskMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(790, Short.MAX_VALUE))
        );

        jMenu1.setText("Productos");

        AgregarProductos.setText("Administrar Productos");
        AgregarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProductosActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarProductos);

        AgregarCategoria.setText("Administrar Categorìas");
        AgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(AgregarCategoria);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Eventos");

        AgregarEventos.setText("Adminsitrar Eventos");
        AgregarEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEventosActionPerformed(evt);
            }
        });
        jMenu4.add(AgregarEventos);

        jmiArqueo.setText("Arqueo de Caja");
        jmiArqueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiArqueoActionPerformed(evt);
            }
        });
        jMenu4.add(jmiArqueo);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Usuarios");

        AdministrarUsuarios.setText("Administrar Usuarios");
        AdministrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministrarUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(AdministrarUsuarios);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Generar Reportes");

        ReporteVentas.setText("Ventas");
        ReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteVentasActionPerformed(evt);
            }
        });
        jMenu5.add(ReporteVentas);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMenu)
        );

        dskMenu.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProductosActionPerformed
        frmProductos ventana = null;
        try {
            ventana = new frmProductos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mnuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dskMenu.add(ventana);
        ventana.show();
        frmProductos.lblUsuario.setText(this.lblUsuario.getText());
    }//GEN-LAST:event_AgregarProductosActionPerformed

    private void AgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCategoriaActionPerformed
        frmCategoria ventana = new frmCategoria();
        this.dskMenu.add(ventana);
        ventana.show();
        frmCategoria.lblUsuario.setText(this.lblUsuario.getText());
    }//GEN-LAST:event_AgregarCategoriaActionPerformed

    private void AgregarEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEventosActionPerformed
        frmEventos ventana = new frmEventos();
        this.dskMenu.add(ventana);
        ventana.show();
        frmEventos.lblUsuario.setText(this.lblUsuario.getText());
    }//GEN-LAST:event_AgregarEventosActionPerformed

    private void AdministrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministrarUsuariosActionPerformed
        frmUsuarios ventana = new frmUsuarios();
        this.dskMenu.add(ventana);
        ventana.show();
        frmUsuarios.lblUser.setText(this.lblUsuario.getText());
    }//GEN-LAST:event_AdministrarUsuariosActionPerformed

    private void ReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteVentasActionPerformed
        frmReporteVenta ventana = new frmReporteVenta();
        this.dskMenu.add(ventana);
        ventana.show();
        frmReporteVenta.lblUsuario.setText(this.lblUsuario.getText());
    }//GEN-LAST:event_ReporteVentasActionPerformed

    private void jmiArqueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiArqueoActionPerformed
        frmArqueo ventana = new frmArqueo();
        this.dskMenu.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jmiArqueoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mnuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mnuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mnuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mnuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mnuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdministrarUsuarios;
    private javax.swing.JMenuItem AgregarCategoria;
    private javax.swing.JMenuItem AgregarEventos;
    private javax.swing.JMenuItem AgregarProductos;
    private javax.swing.JMenuItem ReporteVentas;
    private javax.swing.JDesktopPane dskMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jmiArqueo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
